{% set name = "omero-py" %}
{% set version = "5.10.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version
    }}.tar.gz
  sha256: 5757fc9874ad50641829dbb8e58388055729332d7b48e8be08f2856e885dfe7c

build:
  # Can't use noarch because Windows requirements are different
  # If we remove pywin32 from OMERO.py we could switch to noarch
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
  - VERSION_SUFFIX
  entry_points:
  - omero = omero.main:main

requirements:
  host:
  - pip
  - python
  run:
  - appdirs
  - future
  - numpy
  - pillow
  - python
  - pywin32    # [win]
  - requests
  - pyyaml
  - zeroc-ice36-python

test:
  commands:
  - omero --help
  - omero version
  imports:
  - omero
  - omero.api
  - omero.clients
  - omero.cmd
  - omero.constants
  - omero.fs
  - omero.gateway
  - omero.grid
  - omero.install
  - omero.metadatastore
  - omero.model
  - omero.plugins
  - omero.romio
  - omero.sys
  - omero.util
  - omero_ext

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Python bindings to the OMERO.blitz server
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-py

extra:
  recipe-maintainers:
  - ome
